services:
  database:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=!ChangeMe!
      - POSTGRES_USER=app
      - POSTGRES_DB=app
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db_data:
